retargeting:
  type: position
  urdf_path: shadow_hand/shadow_hand_right.urdf

  target_joint_names: [ 'dummy_x_translation_joint', 'dummy_y_translation_joint', 
                        'dummy_z_translation_joint','dummy_x_rotation_joint', 
                        'dummy_y_rotation_joint','dummy_z_rotation_joint',
                      'FFJ4', 'FFJ3', 'FFJ2', 'FFJ1', 
                      'MFJ4', 'MFJ3', 'MFJ2', 'MFJ1', 'RFJ4', 
                      'RFJ3', 'RFJ2', 'RFJ1', 'LFJ5', 'LFJ4', 
                      'LFJ3', 'LFJ2', 'LFJ1', 'THJ5', 'THJ4', 
                      'THJ3', 'THJ2', 'THJ1']
  target_link_names: [ "thtip", "fftip", "mftip", "rftip", "lftip",
                    "thmiddle","ffmiddle", "mfmiddle", "rfmiddle", "lfdistal",
                    "palm" ,"mfknuckle","rfknuckle",]

  target_link_human_indices: [ 4, 8, 12, 16, 20, 2, 6, 10, 14, 19 ,0,9,13]
  add_dummy_free_joint: True
  weights: [1,1,1,1,1,1,1,1,1,1,1,1]
  # A smaller alpha means stronger filtering, i.e. more smooth but also larger latency
  # 1 means no filter while 0 means not moving
  low_pass_alpha: 1
